stages:
    - test

py-test:
    stage: test
    image: python:3.12
    script:
        -pip install -r requirements.txt
        - echo "Running the tests."
        -python -m pytest --cov-report=html --cov=interactive_topic_modeling
    artifacts:
        paths:
            - coverage
        expire_in: 30 days