stages:
    - build
    - test
    - run

image: python:latest


before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - .\venv\Scripts\activate  # Activating virtual environment in Windows
  - pip install -r requirements.txt



py-test:
  tags:
    - main
  stage: test
  script:
    - echo "Changing directory to interactive_topic_modeling."
    - cd interactive_topic_modeling
    - echo "Running the tests."
    - python -m pytest ..\test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
