stages:
    - build
    - test
    - run

before_script:
  - python3.12 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - export QT_QPA_PLATFORM=offscreen # Required to run in headless mode

py-test:
  tags:
    - main
  stage: test
  script:
    - echo "Changing directory to tommy."
    - cd tommy
    - echo "Running the tests."
    - pytest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
