stages:
    - build
    - test
    - run

image: python:latest


before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - .\venv\Scripts\activate  # Activating virtual environment in Windows



build:
    stage: build
    script:
        - pip install -r requirements.txt
        - echo "building"
        
py-test:
    stage: test
    script:
        - echo "Running the tests."
        - python -m pytest test


run:
  stage: run
  script:
    - echo "run"
    - cd interactive_topic_modeling  # Navigate to the directory
    - python main.py
  dependencies:
    - build
    - py-test