stages:
    - build
    - test
    - run

image: python:latest


before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - .\venv\Scripts\activate  # Activating virtual environment in Windows
  - pip install -r requirements.txt



py-test:
  tags:
    - main
  stage: test
  script:
    - echo "Changing directory to interactive_topic_modeling."
    - cd interactive_topic_modeling
    - echo "Running the tests."
    - python -m pytest ..\test

# This is not doable, we should just use test here and for the rest just deploy on local machines
#run:
#  stage: run
#  script:
#    - echo "run"
#    - cd interactive_topic_modeling  # Navigate to the directory
#    - python main.py

