stages:
    - test

image: python:latest


before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - .\venv\Scripts\activate  # Activating virtual environment in Windows


py-test:
    tags:
    - test
    stage: test
    script:
        - pip install -r requirements.txt
        - pip install six==1.16
        - echo "Running the tests."
        - python -m pytest test
