stages:
    - test

image: python:latest

.windows_job:
  tags:
    - saas-windows-medium-amd64
  before_script:
    - Set-Variable -Name "time" -Value (date -Format "%H:%m")
    - echo ${time}
    - echo "started by ${GITLAB_USER_NAME}"

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


py-test:
    extends:
    - .windows_job
    stage: test
    script:
        - pip install -r requirements.txt
        - echo "Running the tests."
        - python -m pytest --cov-report=html --cov=interactive_topic_modeling
    artifacts:
        paths:
            - coverage
        expire_in: 30 days