stages:
    - build
    - test
    - run

image: python:latest


before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - .\venv\Scripts\activate  # Activating virtual environment in Windows


py-test:
    stage: test
    script:

        - echo "Running the tests."
        - python -m pytest test

build:
    stage: build
    script:
        - pip install -r requirements.txt
        - echo "building"

run:
    stage: run
    script:
        - pip install -r requirements.txt
        - echo "run"
        - python main.py interactive_topic_modeling